In [ ]:
import pandas as pd
import numpy as np
import warnings

warnings.filterwarnings("ignore")

In [ ]:
pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)
pd.set_option("display.max_colwidth", None)

In [ ]:
print("=" * 80)
print("SMART LOGISTICS & SUPPLY CHAIN INTELLIGENCE DASHBOARD")
print("=" * 80)

================================================================================
SMART LOGISTICS & SUPPLY CHAIN INTELLIGENCE DASHBOARD
================================================================================

In [ ]:
df = pd.read_csv("dynamic_supply_chain_logistics_dataset.csv")

In [ ]:
print(df.head())

             timestamp  vehicle_gps_latitude  vehicle_gps_longitude  \
0  2021-01-01 00:00:00             40.375568             -77.014318
1  2021-01-01 01:00:00             33.507818            -117.036902
2  2021-01-01 02:00:00             30.020640             -75.269224
3  2021-01-01 03:00:00             36.649223             -70.190529
4  2021-01-01 04:00:00             30.001279             -70.012195

   fuel_consumption_rate  eta_variation_hours  traffic_congestion_level  \
0               5.136512             4.998009                  5.927586
1               5.101512             0.984929                  1.591992
2               5.090803             4.972665                  8.787765
3               8.219558             3.095064                  0.045257
4               5.000075             3.216077                  8.004851

   warehouse_inventory_level  loading_unloading_time  \
0                 985.716862                4.951392
1                 396.700206                1.030379
2                 832.408935                4.220229
3                   0.573283                0.530186
4                 914.925067                3.620890

   handling_equipment_availability  order_fulfillment_status  \
0                         0.481294                  0.761166
1                         0.620780                  0.196594
2                         0.810933                  0.152742
3                         0.008525                  0.811885
4                         0.020083                  0.053659

   weather_condition_severity  port_congestion_level  shipping_costs  \
0                    0.359066               4.289160      456.503853
1                    0.230660               7.018373      640.408205
2                    0.027210               9.605064      155.749314
3                    0.616619               8.899616      104.317961
4                    0.952385               0.061760      977.222528

   supplier_reliability_score  lead_time_days  historical_demand  \
0                    0.986064        2.128009         100.772854
1                    0.463233       12.608166        5313.738114
2                    0.598561       14.124452        1595.049146
3                    0.742735        3.818972        2530.431941
4                    0.431088       14.001491        2146.190197

   iot_temperature  cargo_condition_status  route_risk_level  \
0         0.574400                0.777263          1.182116
1        -9.753493                0.091839          9.611988
2        -6.491034                0.253529          6.570431
3        -0.151276                0.877576          0.548952
4         2.429448                0.262081          8.861443

   customs_clearance_time  driver_behavior_score  fatigue_monitoring_score  \
0                0.502006               0.033843                  0.978599
1                0.966774               0.201725                  0.918586
2                0.945627               0.264045                  0.394215
3                4.674035               0.362885                  0.905444
4                3.445429               0.016957                  0.258702

   disruption_likelihood_score  delay_probability risk_classification  \
0                     0.506152           0.885291       Moderate Risk
1                     0.980784           0.544178           High Risk
2                     0.998633           0.803322           High Risk
3                     0.993320           0.025977           High Risk
4                     0.912433           0.991122           High Risk

   delivery_time_deviation
0                 9.110682
1                 8.175281
2                 1.283594
3                 9.304897
4                 7.752484

In [ ]:
print(df.shape)

(32065, 26)

In [ ]:
print(df.columns)

Index(['timestamp', 'vehicle_gps_latitude', 'vehicle_gps_longitude',
       'fuel_consumption_rate', 'eta_variation_hours',
       'traffic_congestion_level', 'warehouse_inventory_level',
       'loading_unloading_time', 'handling_equipment_availability',
       'order_fulfillment_status', 'weather_condition_severity',
       'port_congestion_level', 'shipping_costs', 'supplier_reliability_score',
       'lead_time_days', 'historical_demand', 'iot_temperature',
       'cargo_condition_status', 'route_risk_level', 'customs_clearance_time',
       'driver_behavior_score', 'fatigue_monitoring_score',
       'disruption_likelihood_score', 'delay_probability',
       'risk_classification', 'delivery_time_deviation'],
      dtype='object')

In [ ]:
print(df.dtypes)

timestamp                           object
vehicle_gps_latitude               float64
vehicle_gps_longitude              float64
fuel_consumption_rate              float64
eta_variation_hours                float64
traffic_congestion_level           float64
warehouse_inventory_level          float64
loading_unloading_time             float64
handling_equipment_availability    float64
order_fulfillment_status           float64
weather_condition_severity         float64
port_congestion_level              float64
shipping_costs                     float64
supplier_reliability_score         float64
lead_time_days                     float64
historical_demand                  float64
iot_temperature                    float64
cargo_condition_status             float64
route_risk_level                   float64
customs_clearance_time             float64
driver_behavior_score              float64
fatigue_monitoring_score           float64
disruption_likelihood_score        float64
delay_probability                  float64
risk_classification                 object
delivery_time_deviation            float64
dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32065 entries, 0 to 32064
Data columns (total 26 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   timestamp                        32065 non-null  object
 1   vehicle_gps_latitude             32065 non-null  float64
 2   vehicle_gps_longitude            32065 non-null  float64
 3   fuel_consumption_rate            32065 non-null  float64
 4   eta_variation_hours              32065 non-null  float64
 5   traffic_congestion_level         32065 non-null  float64
 6   warehouse_inventory_level        32065 non-null  float64
 7   loading_unloading_time           32065 non-null  float64
 8   handling_equipment_availability  32065 non-null  float64
 9   order_fulfillment_status         32065 non-null  float64
 10  weather_condition_severity       32065 non-null  float64
 11  port_congestion_level            32065 non-null  float64
 12  shipping_costs                   32065 non-null  float64
 13  supplier_reliability_score       32065 non-null  float64
 14  lead_time_days                   32065 non-null  float64
 15  historical_demand                32065 non-null  float64
 16  iot_temperature                  32065 non-null  float64
 17  cargo_condition_status           32065 non-null  float64
 18  route_risk_level                 32065 non-null  float64
 19  customs_clearance_time           32065 non-null  float64
 20  driver_behavior_score            32065 non-null  float64
 21  fatigue_monitoring_score         32065 non-null  float64
 22  disruption_likelihood_score      32065 non-null  float64
 23  delay_probability                32065 non-null  float64
 24  risk_classification              32065 non-null  object
 25  delivery_time_deviation          32065 non-null  float64
dtypes: float64(24), object(2)
memory usage: 6.4+ MB

In [ ]:
df.isnull().sum()

timestamp                          0
vehicle_gps_latitude               0
vehicle_gps_longitude              0
fuel_consumption_rate              0
eta_variation_hours                0
traffic_congestion_level           0
warehouse_inventory_level          0
loading_unloading_time             0
handling_equipment_availability    0
order_fulfillment_status           0
weather_condition_severity         0
port_congestion_level              0
shipping_costs                     0
supplier_reliability_score         0
lead_time_days                     0
historical_demand                  0
iot_temperature                    0
cargo_condition_status             0
route_risk_level                   0
customs_clearance_time             0
driver_behavior_score              0
fatigue_monitoring_score           0
disruption_likelihood_score        0
delay_probability                  0
risk_classification                0
delivery_time_deviation            0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df.shape

(32065, 26)

In [ ]:
df.describe()

,vehicle_gps_latitude,vehicle_gps_longitude,fuel_consumption_rate,eta_variation_hours,traffic_congestion_level,warehouse_inventory_level,loading_unloading_time,handling_equipment_availability,order_fulfillment_status,weather_condition_severity,port_congestion_level,shipping_costs,supplier_reliability_score,lead_time_days,historical_demand,iot_temperature,cargo_condition_status,route_risk_level,customs_clearance_time,driver_behavior_score,fatigue_monitoring_score,disruption_likelihood_score,delay_probability,delivery_time_deviation
count,32065.000000,32065.000000,32065.000000,32065.000000,3.206500e+04,3.206500e+04,32065.000000,3.206500e+04,32065.000000,3.206500e+04,32065.000000,32065.000000,3.206500e+04,32065.000000,32065.000000,32065.000000,3.206500e+04,32065.000000,32065.000000,3.206500e+04,3.206500e+04,32065.000000,32065.000000,32065.000000
mean,38.023589,-90.116648,8.011735,2.893068,4.991493e+00,2.992547e+02,2.291669,3.026954e-01,0.600740,4.976082e-01,6.978414,459.374452,5.008499e-01,5.227502,6022.001286,0.044792,2.972816e-01,7.001144,2.296448,4.983913e-01,6.008723e-01,0.803656,0.699077,5.177648
std,6.917909,17.369244,4.264960,2.274044,3.532048e+00,3.234435e+02,1.554202,3.259146e-01,0.345672,3.532853e-01,3.251051,312.183487,3.535281e-01,4.523085,3427.638017,14.187486,3.216115e-01,3.236328,1.555932,3.541589e-01,3.458101e-01,0.279185,0.324514,4.157988
min,30.000000,-119.999998,5.000000,-1.999993,1.091633e-09,1.322210e-12,0.500000,4.565769e-16,0.000001,4.536949e-09,0.000002,100.000000,6.904319e-10,1.000000,100.002966,-10.000000,7.255415e-19,0.000050,0.500000,4.043927e-09,3.269508e-07,0.000048,0.000003,-1.999998
25%,31.280550,-106.253913,5.019984,1.185744,1.474720e+00,1.605163e+01,0.774798,1.710828e-02,0.277096,1.440135e-01,4.513889,154.017124,1.453158e-01,1.237490,2822.607616,-9.931074,1.678269e-02,4.593407,0.776166,1.443567e-01,2.783148e-01,0.693739,0.456009,1.269197
50%,36.413820,-86.293414,5.636036,3.882059,4.981244e+00,1.572880e+02,1.917121,1.595151e-01,0.680553,4.961781e-01,8.383225,388.996911,5.032655e-01,3.297654,6785.123209,-7.858681,1.549760e-01,8.385605,1.938273,4.988468e-01,6.831130e-01,0.958128,0.839599,6.113662
75%,44.453655,-73.079367,9.669944,4.884355,8.534902e+00,5.405980e+02,3.734188,5.535954e-01,0.938160,8.498226e-01,9.838150,753.007203,8.539780e-01,8.625720,9374.252913,6.024012,5.405408e-01,9.836152,3.750817,8.510762e-01,9.372889e-01,0.998746,0.982391,9.249206
max,50.000000,-70.000000,19.999875,5.000000,9.999999e+00,9.999993e+02,5.000000,9.999995e-01,1.000000,1.000000e+00,10.000000,999.999853,1.000000e+00,14.999995,10000.000000,39.999886,1.000000e+00,10.000000,5.000000,1.000000e+00,1.000000e+00,1.000000,1.000000,10.000000

In [ ]:
df.describe(include="object")

                  timestamp risk_classification
count                 32065               32065
unique                32065                   3
top     2024-08-29 00:00:00           High Risk
freq                      1               23944

In [ ]:
for column in df.columns:
    print("="*60)
    print(column)
    print(df[column].unique())

============================================================
timestamp
['2021-01-01 00:00:00' '2021-01-01 01:00:00' '2021-01-01 02:00:00' ...
 '2024-08-28 22:00:00' '2024-08-28 23:00:00' '2024-08-29 00:00:00']
============================================================
vehicle_gps_latitude
[40.37556848 33.50781834 30.02063979 ... 42.96333786 32.08241013
 38.57648249]
============================================================
vehicle_gps_longitude
[ -77.01431774 -117.03690241  -75.26922404 ...  -82.14987252  -70.0701539
  -94.57954244]
============================================================
fuel_consumption_rate
[5.13651186 5.10151153 5.09080262 ... 5.07159608 5.00000003 5.00004584]
============================================================
eta_variation_hours
[4.99800922 0.98492942 4.9726651  ... 0.4852883  4.759411   4.06843988]
============================================================
traffic_congestion_level
[5.9275858  1.59199219 8.78776535 ... 7.42019975 0.93204989 7.15660841]
============================================================
warehouse_inventory_level
[985.71686153 396.70020577 832.40893488 ...  48.50092018 972.43742475
  16.66970821]
============================================================
loading_unloading_time
[4.95139197 1.03037921 4.22022942 ... 4.99914886 0.50524177 2.20774591]
============================================================
handling_equipment_availability
[0.48129367 0.62078041 0.81093342 ... 0.06436644 0.25094938 0.48601409]
============================================================
order_fulfillment_status
[0.76116617 0.19659403 0.15274152 ... 0.43768722 0.51705119 0.98576127]
============================================================
weather_condition_severity
[0.35906606 0.23065954 0.0272101  ... 0.0223384  0.78233757 0.99763074]
============================================================
port_congestion_level
[4.28915959 7.01837332 9.60506388 ... 0.49823517 9.69746674 7.69364264]
============================================================
shipping_costs
[456.50385304 640.40820539 155.74931357 ... 722.12168652 484.49826055
 202.22982346]
============================================================
supplier_reliability_score
[0.98606428 0.46323299 0.59856055 ... 0.34894862 0.18513048 0.76296532]
============================================================
lead_time_days
[ 2.12800882 12.60816573 14.1244516  ...  1.21222656  6.12943903
  4.25308138]
============================================================
historical_demand
[ 100.77285379 5313.73811428 1595.04914633 ...  600.13281335 1354.43758834
 9742.62480255]
============================================================
iot_temperature
[ 0.57439974 -9.75349321 -6.49103399 ... 29.41087823 -6.95113713
 18.79651454]
============================================================
cargo_condition_status
[0.77726347 0.09183862 0.25352944 ... 0.94964415 0.4073769  0.87652924]
============================================================
route_risk_level
[1.18211599 9.6119883  6.57043129 ... 4.48055234 9.18554948 2.11265543]
============================================================
customs_clearance_time
[0.50200642 0.96677403 0.94562653 ... 0.69098975 4.46220393 2.11838434]
============================================================
driver_behavior_score
[0.03384349 0.20172539 0.264045   ... 0.53710019 0.01289625 0.97404476]
============================================================
fatigue_monitoring_score
[0.97859854 0.91858586 0.39421489 ... 0.89679776 0.46301825 0.75948947]
============================================================
disruption_likelihood_score
[0.50615189 0.98078398 0.9986327  ... 0.44229939 0.99999899 0.99692752]
============================================================
delay_probability
[0.8852912  0.54417765 0.80332203 ... 0.95919721 0.5573401  0.99923029]
============================================================
risk_classification
['Moderate Risk' 'High Risk' 'Low Risk']
============================================================
delivery_time_deviation
[9.11068182 8.17528094 1.28359376 ... 9.79021946 9.95687943 2.09965565]

In [ ]:
for column in df.columns:
    print(f"{column} : {df[column].nunique()}")

timestamp : 32065
vehicle_gps_latitude : 32065
vehicle_gps_longitude : 32065
fuel_consumption_rate : 32037
eta_variation_hours : 32065
traffic_congestion_level : 32065
warehouse_inventory_level : 32065
loading_unloading_time : 32065
handling_equipment_availability : 32065
order_fulfillment_status : 32065
weather_condition_severity : 32065
port_congestion_level : 32065
shipping_costs : 32065
supplier_reliability_score : 32065
lead_time_days : 32065
historical_demand : 32065
iot_temperature : 32031
cargo_condition_status : 32065
route_risk_level : 32065
customs_clearance_time : 32065
driver_behavior_score : 32065
fatigue_monitoring_score : 32065
disruption_likelihood_score : 32030
delay_probability : 32065
risk_classification : 3
delivery_time_deviation : 32065

In [ ]:
df["timestamp"] = pd.to_datetime(df["timestamp"])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32065 entries, 0 to 32064
Data columns (total 26 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   timestamp                        32065 non-null  datetime64[ns]
 1   vehicle_gps_latitude             32065 non-null  float64
 2   vehicle_gps_longitude            32065 non-null  float64
 3   fuel_consumption_rate            32065 non-null  float64
 4   eta_variation_hours              32065 non-null  float64
 5   traffic_congestion_level         32065 non-null  float64
 6   warehouse_inventory_level        32065 non-null  float64
 7   loading_unloading_time           32065 non-null  float64
 8   handling_equipment_availability  32065 non-null  float64
 9   order_fulfillment_status         32065 non-null  float64
 10  weather_condition_severity       32065 non-null  float64
 11  port_congestion_level            32065 non-null  float64
 12  shipping_costs                   32065 non-null  float64
 13  supplier_reliability_score       32065 non-null  float64
 14  lead_time_days                   32065 non-null  float64
 15  historical_demand                32065 non-null  float64
 16  iot_temperature                  32065 non-null  float64
 17  cargo_condition_status           32065 non-null  float64
 18  route_risk_level                 32065 non-null  float64
 19  customs_clearance_time           32065 non-null  float64
 20  driver_behavior_score            32065 non-null  float64
 21  fatigue_monitoring_score         32065 non-null  float64
 22  disruption_likelihood_score      32065 non-null  float64
 23  delay_probability                32065 non-null  float64
 24  risk_classification              32065 non-null  object
 25  delivery_time_deviation          32065 non-null  float64
dtypes: datetime64[ns](1), float64(24), object(1)
memory usage: 6.4+ MB

In [ ]:
print(df["risk_classification"].value_counts())

risk_classification
High Risk        23944
Moderate Risk     5011
Low Risk          3110
Name: count, dtype: int64

In [ ]:
print(df["cargo_condition_status"].describe())

count    3.206500e+04
mean     2.972816e-01
std      3.216115e-01
min      7.255415e-19
25%      1.678269e-02
50%      1.549760e-01
75%      5.405408e-01
max      1.000000e+00
Name: cargo_condition_status, dtype: float64

In [ ]:
print(df["order_fulfillment_status"].describe())

count    32065.000000
mean         0.600740
std          0.345672
min          0.000001
25%          0.277096
50%          0.680553
75%          0.938160
max          1.000000
Name: order_fulfillment_status, dtype: float64

In [ ]:
print(df["handling_equipment_availability"].describe())

count    3.206500e+04
mean     3.026954e-01
std      3.259146e-01
min      4.565769e-16
25%      1.710828e-02
50%      1.595151e-01
75%      5.535954e-01
max      9.999995e-01
Name: handling_equipment_availability, dtype: float64

In [ ]:
print(df["supplier_reliability_score"].describe())

count    3.206500e+04
mean     5.008499e-01
std      3.535281e-01
min      6.904319e-10
25%      1.453158e-01
50%      5.032655e-01
75%      8.539780e-01
max      1.000000e+00
Name: supplier_reliability_score, dtype: float64

In [ ]:
# =============================================================================
# FUNCTION TO CREATE QUARTILE-BASED CATEGORIES
# =============================================================================

def percentile_category(series, labels):
    """
    Categorizes a numeric column into 4 equal-sized groups (quartiles).

    Parameters
    ----------
    series : pandas Series
        Numeric column.

    labels : list
        Four labels for the quartiles.

    Returns
    -------
    pandas Series
        Categorized column.
    """

    return pd.qcut(
        series.rank(method="first"),
        q=4,
        labels=labels
    )

In [ ]:
# =============================================================================
# CREATE SUPPLIER GRADE
# =============================================================================

df["Supplier_Grade"] = percentile_category(
    df["supplier_reliability_score"],
    ["C", "B", "A", "A+"]
)

In [ ]:
df["Supplier_Grade"].value_counts()

Supplier_Grade
C     8017
B     8016
A     8016
A+    8016
Name: count, dtype: int64

In [ ]:
df["Supplier_Grade"].value_counts()

Supplier_Grade
C     8017
B     8016
A     8016
A+    8016
Name: count, dtype: int64

In [ ]:
df["Supplier_Grade"].value_counts()

Supplier_Grade
C     8017
B     8016
A     8016
A+    8016
Name: count, dtype: int64

In [ ]:
# =============================================================================
# SUPPLIER RANK
# =============================================================================

supplier_rank = {
    "A+": 1,
    "A": 2,
    "B": 3,
    "C": 4
}

df["Supplier_Rank"] = df["Supplier_Grade"].map(supplier_rank)

In [ ]:
df[["Supplier_Grade", "Supplier_Rank"]].head()

  Supplier_Grade Supplier_Rank
0             A+             1
1              B             3
2              A             2
3              A             2
4              B             3

In [ ]:

fuel_min = df["fuel_consumption_rate"].min()
fuel_max = df["fuel_consumption_rate"].max()

df["Fuel_Score"] = (
    (fuel_max - df["fuel_consumption_rate"])
    / (fuel_max - fuel_min)
) * 100

In [ ]:
df["Fuel_Score"].describe()

count    32065.000000
mean        79.921600
std         28.433304
min          0.000000
25%         68.866783
50%         95.759726
75%         99.866773
max        100.000000
Name: Fuel_Score, dtype: float64

In [ ]:


df["Fuel_Efficiency"] = percentile_category(
    -df["fuel_consumption_rate"],
    ["Poor", "Average", "Good", "Excellent"]
)

In [ ]:
df["Fuel_Efficiency"].value_counts()

Fuel_Efficiency
Poor         8017
Average      8016
Good         8016
Excellent    8016
Name: count, dtype: int64

In [ ]:


fuel_rank = {
    "Excellent": 1,
    "Good": 2,
    "Average": 3,
    "Poor": 4
}

df["Fuel_Rank"] = df["Fuel_Efficiency"].map(fuel_rank)

In [ ]:
df[["Fuel_Efficiency","Fuel_Rank"]].head()

  Fuel_Efficiency Fuel_Rank
0            Good         2
1            Good         2
2            Good         2
3         Average         3
4       Excellent         1

In [ ]:
df["Driver_Score"] = df["driver_behavior_score"] * 100

In [ ]:
df["Driver_Score"].describe()

count    3.206500e+04
mean     4.983913e+01
std      3.541589e+01
min      4.043927e-07
25%      1.443567e+01
50%      4.988468e+01
75%      8.510762e+01
max      1.000000e+02
Name: Driver_Score, dtype: float64

In [ ]:
df["Driver_Grade"] = percentile_category(
    df["driver_behavior_score"],
    ["Poor", "Average", "Good", "Excellent"]
)

In [ ]:
df["Driver_Grade"].value_counts()

Driver_Grade
Poor         8017
Average      8016
Good         8016
Excellent    8016
Name: count, dtype: int64

In [ ]:
driver_rank = {
    "Excellent": 1,
    "Good": 2,
    "Average": 3,
    "Poor": 4
}

df["Driver_Rank"] = df["Driver_Grade"].map(driver_rank)

In [ ]:
df[["Driver_Grade","Driver_Rank"]].head()

  Driver_Grade Driver_Rank
0         Poor           4
1      Average           3
2      Average           3
3      Average           3
4         Poor           4

In [ ]:
df["Fatigue_Score"] = (
    1 - df["fatigue_monitoring_score"]
) * 100

In [ ]:
df["Fatigue_Score"].describe()

count    3.206500e+04
mean     3.991277e+01
std      3.458101e+01
min      3.124390e-10
25%      6.271112e+00
50%      3.168870e+01
75%      7.216852e+01
max      9.999997e+01
Name: Fatigue_Score, dtype: float64

In [ ]:
df["Fatigue_Level"] = percentile_category(
    -df["fatigue_monitoring_score"],
    ["Critical", "High", "Moderate", "Low"]
)

In [ ]:
df["Fatigue_Level"].value_counts()

Fatigue_Level
Critical    8017
High        8016
Moderate    8016
Low         8016
Name: count, dtype: int64

In [ ]:
fatigue_rank = {
    "Low": 1,
    "Moderate": 2,
    "High": 3,
    "Critical": 4
}

df["Fatigue_Rank"] = df["Fatigue_Level"].map(fatigue_rank)

In [ ]:
df["Fleet_Performance_Score"] = (
    df["Driver_Score"] * 0.40 +
    df["Fuel_Score"] * 0.35 +
    df["Fatigue_Score"] * 0.25
).round(2)

In [ ]:
df["Fleet_Status"] = percentile_category(
    df["Fleet_Performance_Score"],
    ["Critical", "Needs Attention", "Good", "Excellent"]
)

In [ ]:
eta_abs = df["eta_variation_hours"].abs()

df["ETA_Score"] = (
    (eta_abs.max() - eta_abs) /
    (eta_abs.max() - eta_abs.min())
) * 100

In [ ]:
df["ETA_Score"].describe()

count    32065.000000
mean        34.414579
std         33.387094
min          0.000000
25%          2.313175
50%         22.361478
75%         65.666654
max        100.000000
Name: ETA_Score, dtype: float64

In [ ]:
df["ETA_Category"] = percentile_category(
    df["ETA_Score"],
    ["Critical", "Delayed", "On Schedule", "Excellent"]
)

In [ ]:
eta_rank = {
    "Excellent":1,
    "On Schedule":2,
    "Delayed":3,
    "Critical":4
}

df["ETA_Rank"] = df["ETA_Category"].map(eta_rank)

In [ ]:
eta_rank = {
    "Excellent":1,
    "On Schedule":2,
    "Delayed":3,
    "Critical":4
}

df["ETA_Rank"] = df["ETA_Category"].map(eta_rank)

In [ ]:
lead_min = df["lead_time_days"].min()
lead_max = df["lead_time_days"].max()

df["LeadTime_Score"] = (
    (lead_max - df["lead_time_days"])
    /
    (lead_max - lead_min)
) * 100

In [ ]:
df["LeadTime_Score"].describe()

count    32065.000000
mean        69.803547
std         32.307760
min          0.000000
25%         45.530551
50%         83.588183
75%         98.303643
max        100.000000
Name: LeadTime_Score, dtype: float64

In [ ]:
df["LeadTime_Category"] = percentile_category(
    df["LeadTime_Score"],
    ["Poor", "Average", "Good", "Excellent"]
)

In [ ]:
df["LeadTime_Category"].value_counts()

LeadTime_Category
Poor         8017
Average      8016
Good         8016
Excellent    8016
Name: count, dtype: int64

In [ ]:
lead_rank = {
    "Excellent":1,
    "Good":2,
    "Average":3,
    "Poor":4
}

df["LeadTime_Rank"] = df["LeadTime_Category"].map(lead_rank)

In [ ]:
df["Delay_Category"] = percentile_category(
    df["delay_probability"],
    ["Low", "Moderate", "High", "Critical"]
)

In [ ]:
delay_rank = {
    "Low":1,
    "Moderate":2,
    "High":3,
    "Critical":4
}

df["Delay_Rank"] = df["Delay_Category"].map(delay_rank)

In [ ]:
df["Route_Efficiency_Score"] = (
    df["ETA_Score"] * 0.40 +
    df["LeadTime_Score"] * 0.35 +
    ((1 - df["delay_probability"]) * 100) * 0.25
).round(2)

In [ ]:
df["Route_Status"] = percentile_category(
    df["Route_Efficiency_Score"],
    ["Critical", "Needs Attention", "Efficient", "Highly Efficient"]
)

In [ ]:
route_rank = {
    "Highly Efficient":1,
    "Efficient":2,
    "Needs Attention":3,
    "Critical":4
}

df["Route_Rank"] = df["Route_Status"].map(route_rank)

In [ ]:
inventory_min = df["warehouse_inventory_level"].min()
inventory_max = df["warehouse_inventory_level"].max()

df["Inventory_Score"] = (
    (df["warehouse_inventory_level"] - inventory_min)
    /
    (inventory_max - inventory_min)
) * 100

In [ ]:
df["Inventory_Status"] = percentile_category(
    df["Inventory_Score"],
    ["Critical", "Low", "Healthy", "Optimal"]
)

In [ ]:
inventory_rank = {
    "Optimal":1,
    "Healthy":2,
    "Low":3,
    "Critical":4
}

df["Inventory_Rank"] = df["Inventory_Status"].map(inventory_rank)

In [ ]:
df["Equipment_Score"] = (
    df["handling_equipment_availability"] * 100
)

In [ ]:
df["Equipment_Status"] = percentile_category(
    df["handling_equipment_availability"],
    ["Poor", "Average", "Good", "Excellent"]
)

In [ ]:
equipment_rank = {
    "Excellent":1,
    "Good":2,
    "Average":3,
    "Poor":4
}

df["Equipment_Rank"] = df["Equipment_Status"].map(equipment_rank)

In [ ]:
loading_min = df["loading_unloading_time"].min()
loading_max = df["loading_unloading_time"].max()

loading_score = (
    (loading_max - df["loading_unloading_time"])
    /
    (loading_max - loading_min)
) * 100

df["Warehouse_Efficiency_Score"] = (
    df["Inventory_Score"] * 0.40 +
    df["Equipment_Score"] * 0.35 +
    loading_score * 0.25
).round(2)

In [ ]:
df["Warehouse_Health"] = percentile_category(
    df["Warehouse_Efficiency_Score"],
    ["Critical", "Needs Attention", "Healthy", "Excellent"]
)

In [ ]:
warehouse_rank = {
    "Excellent":1,
    "Healthy":2,
    "Needs Attention":3,
    "Critical":4
}

df["Warehouse_Rank"] = df["Warehouse_Health"].map(warehouse_rank)

In [ ]:
df["Shipping_Cost_Category"] = percentile_category(
    df["shipping_costs"],
    ["Low Cost", "Medium Cost", "High Cost", "Premium Cost"]
)

In [ ]:
shipping_rank = {
    "Low Cost":1,
    "Medium Cost":2,
    "High Cost":3,
    "Premium Cost":4
}

df["Shipping_Cost_Rank"] = df["Shipping_Cost_Category"].map(shipping_rank)

In [ ]:
df["Supplier_Risk"] = percentile_category(
    -df["supplier_reliability_score"],
    ["Critical", "High", "Moderate", "Low"]
)

In [ ]:
df["Weather_Category"] = percentile_category(
    df["weather_condition_severity"],
    ["Clear", "Moderate", "Severe", "Extreme"]
)

In [ ]:
weather_rank = {
    "Clear":1,
    "Moderate":2,
    "Severe":3,
    "Extreme":4
}

df["Weather_Rank"] = df["Weather_Category"].map(weather_rank)

In [ ]:
df["Traffic_Category"] = percentile_category(
    df["traffic_congestion_level"],
    ["Light", "Moderate", "Heavy", "Severe"]
)

In [ ]:
traffic_rank = {
    "Light":1,
    "Moderate":2,
    "Heavy":3,
    "Severe":4
}

df["Traffic_Rank"] = df["Traffic_Category"].map(traffic_rank)

In [ ]:
df["Port_Category"] = percentile_category(
    df["port_congestion_level"],
    ["Low", "Moderate", "High", "Critical"]
)

In [ ]:
port_rank = {
    "Low":1,
    "Moderate":2,
    "High":3,
    "Critical":4
}

df["Port_Rank"] = df["Port_Category"].map(port_rank)

In [ ]:
df["Disruption_Category"] = percentile_category(
    df["disruption_likelihood_score"],
    ["Low", "Moderate", "High", "Critical"]
)

In [ ]:
weather_score = (1 - df["weather_condition_severity"]) * 100

traffic_score = (
    (10 - df["traffic_congestion_level"]) / 10
) * 100

port_score = (
    (10 - df["port_congestion_level"]) / 10
) * 100

df["External_Risk_Score"] = (
    weather_score * 0.35 +
    traffic_score * 0.35 +
    port_score * 0.30
).round(2)

In [ ]:
route_score = (
    (10 - df["route_risk_level"]) / 10
) * 100

delay_score = (
    (1 - df["delay_probability"]) * 100
)

disruption_score = (
    (1 - df["disruption_likelihood_score"]) * 100
)

df["Operational_Risk_Score"] = (
    delay_score * 0.30 +
    disruption_score * 0.30 +
    route_score * 0.20 +
    df["External_Risk_Score"] * 0.20
).round(2)

In [ ]:
df["Logistics_Health_Score"] = (
    df["Fleet_Performance_Score"] * 0.25 +
    df["Warehouse_Efficiency_Score"] * 0.25 +
    df["Route_Efficiency_Score"] * 0.25 +
    df["Operational_Risk_Score"] * 0.25
).round(2)

In [ ]:
df["Logistics_Health"] = percentile_category(
    df["Logistics_Health_Score"],
    [
        "Critical",
        "Needs Attention",
        "Healthy",
        "Excellent"
    ]
)

In [ ]:
logistics_rank = {
    "Excellent":1,
    "Healthy":2,
    "Needs Attention":3,
    "Critical":4
}

df["Logistics_Rank"] = df["Logistics_Health"].map(logistics_rank)

In [ ]:
conditions = [
    df["Logistics_Health_Score"] >= 85,
    df["Logistics_Health_Score"] >= 70,
    df["Logistics_Health_Score"] >= 50
]

choices = [
    "Low",
    "Medium",
    "High"
]

df["Shipment_Priority"] = np.select(
    conditions,
    choices,
    default="Critical"
)

In [ ]:
conditions = [
    df["Logistics_Health_Score"] >= 85,
    df["Logistics_Health_Score"] >= 70,
    df["Logistics_Health_Score"] >= 50
]

recommendations = [
    "Normal Operations",
    "Monitor Closely",
    "Priority Handling"
]

df["Executive_Recommendation"] = np.select(
    conditions,
    recommendations,
    default="Immediate Intervention"
)

In [ ]:
conditions = [
    df["Logistics_Health_Score"] >= 85,
    df["Logistics_Health_Score"] >= 70,
    df["Logistics_Health_Score"] >= 50
]

recommendations = [
    "Normal Operations",
    "Monitor Closely",
    "Priority Handling"
]

df["Executive_Recommendation"] = np.select(
    conditions,
    recommendations,
    default="Immediate Intervention"
)

In [ ]:
# =============================================================================
# ENGINEERED COLUMNS
# =============================================================================

new_columns = [

'Supplier_Grade',
'Supplier_Rank',

'Fuel_Score',
'Fuel_Efficiency',
'Fuel_Rank',

'Driver_Score',
'Driver_Grade',
'Driver_Rank',

'Fatigue_Score',
'Fatigue_Level',
'Fatigue_Rank',

'Fleet_Performance_Score',
'Fleet_Status',

'ETA_Score',
'ETA_Category',
'ETA_Rank',

'LeadTime_Score',
'LeadTime_Category',
'LeadTime_Rank',

'Delay_Category',
'Delay_Rank',

'Route_Efficiency_Score',
'Route_Status',
'Route_Rank',

'Inventory_Score',
'Inventory_Status',
'Inventory_Rank',

'Equipment_Score',
'Equipment_Status',
'Equipment_Rank',

'Warehouse_Efficiency_Score',
'Warehouse_Health',
'Warehouse_Rank',

'Shipping_Cost_Category',
'Shipping_Cost_Rank',

'Supplier_Risk',

'Weather_Category',
'Weather_Rank',

'Traffic_Category',
'Traffic_Rank',

'Port_Category',
'Port_Rank',

'Disruption_Category',

'External_Risk_Score',

'Operational_Risk_Score',

'Logistics_Health_Score',

'Logistics_Health',

'Logistics_Rank',

'Shipment_Priority',

'Executive_Recommendation'

]

print(df[new_columns].head())

  Supplier_Grade Supplier_Rank  Fuel_Score Fuel_Efficiency Fuel_Rank  \
0             A+             1   99.089913            Good         2
1              B             3   99.323251            Good         2
2              A             2   99.394644            Good         2
3              A             2   78.536105         Average         3
4              B             3   99.999501       Excellent         1

   Driver_Score Driver_Grade Driver_Rank  Fatigue_Score Fatigue_Level  \
0      3.384349         Poor           4       2.140146      Critical
1     20.172539      Average           3       8.141414          High
2     26.404500      Average           3      60.578511      Moderate
3     36.288516      Average           3       9.455622          High
4      1.695749         Poor           4      74.129806           Low

  Fatigue_Rank  Fleet_Performance_Score     Fleet_Status  ETA_Score  \
0            4                    36.57         Critical   0.039820
1            3                    44.87  Needs Attention  80.310975
2            2                    60.49             Good   0.546763
3            3                    44.37  Needs Attention  38.103266
4            1                    54.21  Needs Attention  35.682714

  ETA_Category ETA_Rank  LeadTime_Score LeadTime_Category LeadTime_Rank  \
0     Critical        4       91.942792              Good             2
1    Excellent        1       17.084504              Poor             4
2     Critical        4        6.253887              Poor             4
3  On Schedule        2       79.864476           Average             3
4  On Schedule        2        7.132176              Poor             4

  Delay_Category Delay_Rank  Route_Efficiency_Score      Route_Status  \
0           High          3                   35.06   Needs Attention
1       Moderate          2                   49.50         Efficient
2       Moderate          2                    7.32          Critical
3            Low          1                   67.54  Highly Efficient
4       Critical          4                   16.99          Critical

  Route_Rank  Inventory_Score Inventory_Status Inventory_Rank  \
0          3        98.571755          Optimal              1
1          2        39.670048          Healthy              2
2          4        83.240952          Optimal              1
3          1         0.057328         Critical              4
4          4        91.492571          Optimal              1

   Equipment_Score Equipment_Status Equipment_Rank  \
0        48.129367             Good              2
1        62.078041        Excellent              1
2        81.093342        Excellent              1
3         0.852505             Poor              4
4         2.008343          Average              3

   Warehouse_Efficiency_Score Warehouse_Health Warehouse_Rank  \
0                       56.54        Excellent              1
1                       59.65        Excellent              1
2                       66.01        Excellent              1
3                       25.15  Needs Attention              3
4                       44.96          Healthy              2

  Shipping_Cost_Category Shipping_Cost_Rank Supplier_Risk Weather_Category  \
0              High Cost                  3      Critical         Moderate
1              High Cost                  3      Moderate         Moderate
2            Medium Cost                  2          High            Clear
3               Low Cost                  1          High           Severe
4           Premium Cost                  4      Moderate          Extreme

  Weather_Rank Traffic_Category Traffic_Rank Port_Category Port_Rank  \
0            2            Heavy            3           Low         1
1            2         Moderate            2      Moderate         2
2            1           Severe            4          High         3
3            3            Light            1          High         3
4            4            Heavy            3           Low         1

  Disruption_Category  External_Risk_Score  Operational_Risk_Score  \
0                 Low                53.82                   46.66
1                High                65.30                   28.09
2                High                39.48                   20.70
3                High                51.56                   58.64
4            Moderate                38.46                   12.86

   Logistics_Health_Score Logistics_Health Logistics_Rank Shipment_Priority  \
0                   43.71          Healthy              2          Critical
1                   45.53          Healthy              2          Critical
2                   38.63  Needs Attention              3          Critical
3                   48.92          Healthy              2          Critical
4                   32.25         Critical              4          Critical

  Executive_Recommendation
0   Immediate Intervention
1   Immediate Intervention
2   Immediate Intervention
3   Immediate Intervention
4   Immediate Intervention

In [ ]:
# =============================================================================
# EXECUTIVE SUMMARY
# =============================================================================

print("="*80)

print("EXECUTIVE SUMMARY")

print("="*80)

print("\nAverage Logistics Health")

print(round(df["Logistics_Health_Score"].mean(),2))

print("\nAverage Fleet Performance")

print(round(df["Fleet_Performance_Score"].mean(),2))

print("\nAverage Warehouse Efficiency")

print(round(df["Warehouse_Efficiency_Score"].mean(),2))

print("\nAverage Route Efficiency")

print(round(df["Route_Efficiency_Score"].mean(),2))

print("\nAverage Operational Risk")

print(round(df["Operational_Risk_Score"].mean(),2))

================================================================================
EXECUTIVE SUMMARY
================================================================================

Average Logistics Health
42.74

Average Fleet Performance
57.89

Average Warehouse Efficiency
37.61

Average Route Efficiency
45.72

Average Operational Risk
29.75

In [ ]:
float_cols = df.select_dtypes(include="float64").columns

df[float_cols] = df[float_cols].astype("float32")

int_cols = df.select_dtypes(include="int64").columns

df[int_cols] = df[int_cols].astype("int32")

In [ ]:
print(df.shape)

print(df.info())

(32065, 76)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32065 entries, 0 to 32064
Data columns (total 76 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   timestamp                        32065 non-null  datetime64[ns]
 1   vehicle_gps_latitude             32065 non-null  float32
 2   vehicle_gps_longitude            32065 non-null  float32
 3   fuel_consumption_rate            32065 non-null  float32
 4   eta_variation_hours              32065 non-null  float32
 5   traffic_congestion_level         32065 non-null  float32
 6   warehouse_inventory_level        32065 non-null  float32
 7   loading_unloading_time           32065 non-null  float32
 8   handling_equipment_availability  32065 non-null  float32
 9   order_fulfillment_status         32065 non-null  float32
 10  weather_condition_severity       32065 non-null  float32
 11  port_congestion_level            32065 non-null  float32
 12  shipping_costs                   32065 non-null  float32
 13  supplier_reliability_score       32065 non-null  float32
 14  lead_time_days                   32065 non-null  float32
 15  historical_demand                32065 non-null  float32
 16  iot_temperature                  32065 non-null  float32
 17  cargo_condition_status           32065 non-null  float32
 18  route_risk_level                 32065 non-null  float32
 19  customs_clearance_time           32065 non-null  float32
 20  driver_behavior_score            32065 non-null  float32
 21  fatigue_monitoring_score         32065 non-null  float32
 22  disruption_likelihood_score      32065 non-null  float32
 23  delay_probability                32065 non-null  float32
 24  risk_classification              32065 non-null  object
 25  delivery_time_deviation          32065 non-null  float32
 26  Supplier_Grade                   32065 non-null  category
 27  Supplier_Rank                    32065 non-null  category
 28  Fuel_Score                       32065 non-null  float32
 29  Fuel_Efficiency                  32065 non-null  category
 30  Fuel_Rank                        32065 non-null  category
 31  Driver_Score                     32065 non-null  float32
 32  Driver_Grade                     32065 non-null  category
 33  Driver_Rank                      32065 non-null  category
 34  Fatigue_Score                    32065 non-null  float32
 35  Fatigue_Level                    32065 non-null  category
 36  Fatigue_Rank                     32065 non-null  category
 37  Fleet_Performance_Score          32065 non-null  float32
 38  Fleet_Status                     32065 non-null  category
 39  ETA_Score                        32065 non-null  float32
 40  ETA_Category                     32065 non-null  category
 41  ETA_Rank                         32065 non-null  category
 42  LeadTime_Score                   32065 non-null  float32
 43  LeadTime_Category                32065 non-null  category
 44  LeadTime_Rank                    32065 non-null  category
 45  Delay_Category                   32065 non-null  category
 46  Delay_Rank                       32065 non-null  category
 47  Route_Efficiency_Score           32065 non-null  float32
 48  Route_Status                     32065 non-null  category
 49  Route_Rank                       32065 non-null  category
 50  Inventory_Score                  32065 non-null  float32
 51  Inventory_Status                 32065 non-null  category
 52  Inventory_Rank                   32065 non-null  category
 53  Equipment_Score                  32065 non-null  float32
 54  Equipment_Status                 32065 non-null  category
 55  Equipment_Rank                   32065 non-null  category
 56  Warehouse_Efficiency_Score       32065 non-null  float32
 57  Warehouse_Health                 32065 non-null  category
 58  Warehouse_Rank                   32065 non-null  category
 59  Shipping_Cost_Category           32065 non-null  category
 60  Shipping_Cost_Rank               32065 non-null  category
 61  Supplier_Risk                    32065 non-null  category
 62  Weather_Category                 32065 non-null  category
 63  Weather_Rank                     32065 non-null  category
 64  Traffic_Category                 32065 non-null  category
 65  Traffic_Rank                     32065 non-null  category
 66  Port_Category                    32065 non-null  category
 67  Port_Rank                        32065 non-null  category
 68  Disruption_Category              32065 non-null  category
 69  External_Risk_Score              32065 non-null  float32
 70  Operational_Risk_Score           32065 non-null  float32
 71  Logistics_Health_Score           32065 non-null  float32
 72  Logistics_Health                 32065 non-null  category
 73  Logistics_Rank                   32065 non-null  category
 74  Shipment_Priority                32065 non-null  object
 75  Executive_Recommendation         32065 non-null  object
dtypes: category(35), datetime64[ns](1), float32(37), object(3)
memory usage: 6.6+ MB
None

In [ ]:
df.to_csv(
    "Smart_Logistics_Dashboard_Final.csv",
    index=False
)

print("="*80)

print("DATASET EXPORTED SUCCESSFULLY")

print("="*80)

print("Filename : Smart_Logistics_Dashboard_Final.csv")

================================================================================
DATASET EXPORTED SUCCESSFULLY
================================================================================
Filename : Smart_Logistics_Dashboard_Final.csv